import socket

SERVER_HOST=socket.gethostname()
SERVER_PORT=9999

SERVER_RESPONSE_SUCCESS = 0
SERVER_RESPONSE_ROOM_ALREADY_EXISTS = 1
SERVER_RESPONSE_ROOM_DOESNOT_EXIST = 2
SERVER_RESPONSE_ROOM_NO_ROOMS = 3